# Generated by Django 5.2.15 on 2026-07-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='COLLAGE',
            new_name='College',
        ),
        migrations.RenameModel(
            old_name='SKILLS',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='degree',
            old_name='collage',
            new_name='college',
        ),
    ]
